### ISSUE TITLE
Návrh databáze

### ISSUE THREAD

**Issue by malinajan** [kmzbrnoI/members-db#1]
Aktuální databáze je jeden velký mess. Navrhnout pořádně.

### Lidé

* (asi naše vnitřní id)
* Příjmení
* Jméno
* Titul
* Rodné číslo
* (Datum narození? Možná nějak počítat z rodného čísla)
* Ulice, číslo
* Město
* PSČ
* Telefon
* e-mail
* Číslo licence SMČR
* Fotka?

### Členství

Je třeba nějak modelovat členství. Každý člověk může být ne/členem na granularitě jednoho roku. Asi tabulka rok-člověkid. Tabulka se bude plnit podle toho, jak lidi zaplatí příspěvky.

### Příspěvky

Aktuální tabulka obsahuje číslo zaplaceného příspěvku pro každého člena a rok. Zvážit, jestli chceme ukládat hodnotu peněz. Stačí jedna tabulka rok-výše příspěvku?

### Log členství

U každého člena a změny jeho členství asi chceme ukládat nějakou poznámku, typicky "proč". Příklad: "řádný vstup do klubu", "úmrtí", "vystoupení na vlastní žádost", ...

## Co je ve staré databázi a podle Honzy nemá smysl zachovávat

* Hodnota člena – adjunkt, vozmistr, strojvedoucí, ...
  - Zbytečná data navíc, oprávnění si drží hJOPka.
* Zaškolení člena na stanice.
  - Zbytečně specifická věc, držet v externím systému (hJOP).
* Dovednosti u každého člena: umí vystřihovánky, umí stavebnice z leptu, umí patinu, ...

## TODOs

* [ ] Pojmenovat atributy česky nebo anglicky?
* [ ] Chceme ukládat něco jako "funkci"? Kdo je v radě apod. Asi nemá smysl...
* [ ] Budeme nějak propojovat třeba s hJOP databází? Pořádně rozmyslet, kam všude chceme dělat exporty dat a podle toho navrhnout.
* [ ] Je třeba vyřešit, kde bude uloženo kdo má do databáze jaký přístup, asi atribut nebo další tabulka. 
* [ ] Ukládat u uživatelů kontaktní e-mail a e-mail na přístup k Drivu?
